.\" @(#)gcin2tab.1		-*- nroff -*-
.\"-------
.TH GCIN2TAB 1 "26 MAY 2005" "GCIN TOOLS"
.SH NAME
gcin2tab, phoa2d, phod2a, tsa2d, tsd2a, tslearn \- gcin associated tools
.SH SYNOPSIS
.B gcin2tab
.RI [FILE]
.br
.B phoa2d
.br
.B phod2a
.br
.B tsa2d
.br
.B tsd2a
.br
.B tslearn
.SH DESCRIPTION
.B gcin2tab
is a tool to convert original cin-format IM table into gtab-format file for gcin.
.br
\fB \fP 
\fBphoa2d\fP is a tool to convert $HOME/.gcin/pho.tab.src into $HOME/.gcin/pho.tab, which is used by Bopomofo and Tsin IM.
.br
\fB \fP
\fBphod2a\fP is a tool to convert $HOME/.gcin/pho.tab into $HOME/.gcin/pho.tab.src, which may be edited by users.
.br
\fB \fP
\fBtsa2d\fP and \fBtsd2a\fP are tools for importing and exporting Tsin IM phrase database.
.br
\fB \fP
\fBtslearn\fP is a tool for learning user's personal Tsin data online.
.SH SEE ALSO
.IR gcin (1),
.IR gcin-setup (1)
.SH AUTHOR
.IP "Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>"
Wrote gcin and those tools listed above.
