.TH "GCIN" "1" "28 AUG 2006" "GCIN 1.2.3" "gcin input method platform"
.SH "NAME" 
gcin, gcin-setup \- an input method server
.SH "SYNOPSIS" 
\fBgcin\fP
.RB [\| \-h \||\| \-v \||\| \--version \|]
.br
\fBgcin-setup\fP
.SH "DESCRIPTION" 
\fBgcin\fP is an input method(IM) server, which focused mainly on Traditional Chinese. It is also very useful for Simplified Chinese, Japanese, and many other languages. IM table format of gcin is almost as same as those of scim and xcin. Users may append their IMs to gcin very easily. The "g" of gcin means that it features a better GTK+2 user interface.
.PP
\fBgcin-setup\fP is gcin's setting tool. However, its interface is Traditional Chinese only. Another configure method is writing conffiles in $HOME/.gcin/config. See the CONFFILES section below.
.SH "OPTIONS"
.PP
.IP "\-h, \-v, \-\-version"
Show version of gcin and exit. gcin-setup has no those options.
.SH "FILES" 
.IP "/usr/share/gcin/table/gtab.list"
Input methods available for gcin. You may copy it to $HOME/.gcin/ and edit it as you like. If you have no $HOME/.gcin/gtab.list, /usr/share/gcin/table/gtab.list will be used.
.IP "/usr/share/gcin/script/utf8-edit"
A file helps gcin finding text editors when needed. You may add any UTF-8 compatible text editor you like into it.
.SH ENVIRONMENT VARIABLES 
.IP "LC_CTYPE"        
For bash: export LC_CTYPE=zh_TW.UTF-8
.br
For csh: setenv LC_CTYPE zh_TW.Big5
.IP "XMODIFIERS"
For bash: export XMODIFIERS=@im=gcin
.br
For csh: setenv XMODIFIERS @im=gcin
.IP "GTK_IM_MODULE"
For bash: export GTK_IM_MODULE=gcin
.br
For csh: setenv GTK_IM_MODULE gcin
.IP "QT_IM_MODULE"
For bash: export QT_IM_MODULE=gcin
.br
For csh: setenv QT_IM_MODULE gcin
.IP "GCIN_CONNECT_MSG_ON"
Display messages for socket connections.
.IP "GCIN_DBG_TMP"
Display additional debug messages.
.IP "GCIN_DUAL_XIM_OFF"
Disable dual XIM server feature.
.IP "GCIN_ERR_COREDUMP"
Option for debugging.
.IP "GCIN_IM_CLIENT_NO_AUTO_EXEC"
Disable gcin protocol's auto-evoked feature.
.IP "GCIN_TABLE_DIR"
Assign IM tables' directory other then /usr/share/gcin/table.
.IP "GCIN_XIM"
Assign gcin XIM server's XIM name.
.SH "CONFFILES" 
If you can read Traditional Chinese, use gcin-setup and skip this secion.
.PP
If you really want to write conffiles by hand, you may execute those commands:
.PP
mkdir -p $HOME/.gcin/config
.br
echo zo > $HOME/.gcin/config/phonetic-keyboard
.PP
Thus you make a \fBphonetic-keyboard\fP file with content \fBzo\fP, which means you select standard style with 1234 selection method.
.PP
Available conffiles are listed below, and default options are showed \fBbold\fP.
.PP
If you use \fBgcin-setup\fP, those directories and files will be created automatically. You may not want to do it all by yourself.
.IP "\fB$HOME/.gcin/config/phonetic-keyboard\fP \fIstring\fP"
Key codes arrangement style within Bopomofo and Tsin intelligent input method(Tsin IM).
.PP
OPTIONS    MEANINGS
.br
\fBzo         Standard style with 1234 selection method\fP
.br
zo-asdf    Standard style with asdf selection method
.br
et         Eten style with 1234 selection method
.br
et-asdf    Eten style with asdf selection method
.br
et26       Eten 26 keys style with 1234 selection method
.br
et26-asdf  Eten 26 keys style with asdf selection method
.br
hsu        Mr. Hsu's style (Kuo-Yin IM, Natural Bopomofo IM)
.br
ibm        IBM's style
.IP "\fB$HOME/.gcin/config/tsin-chinese-english-toggle_key\fP \fInumber\fP" 
Toggle key for Chinese/English Mode within Tsin IM.
.PP
OPTIONS    MEANINGS
.br
\fB1          Caps Lock key\fP
.br
2          Tab key
.br
4          Shift key(Not available under XIM mode).
.IP "\fB$HOME/.gcin/config/tsin-space-opt\fP \fInumber\fP" 
Function of Space key within Tsin IM.
.PP
OPTIONS    MEANINGS
.br
\fB1          Select other same phonetic characters.\fP
.br
2          Send contents of editing area to application.
.IP "\fB$HOME/.gcin/config/tsin-phrase-pre-select\fP \fIboolean\fP" 
Show phrase pre-selection window within Tsin IM.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/phonetic-char-dynamic-sequence\fP \fIboolean\fP" 
Dynamic character sequence adjustment within Bopomofo and Tsin IM.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/pho-simple-window\fP \fIboolean\fP" 
Smaller window for Bopomofo and Tsin IM.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/pho-hide-row2\fP \fIboolean\fP"
Hide second row of Bopomofo and Tsin IMs' window.
.PP
OPTIONS    MEANINGS
.br
1          ON
.br
\fB0          OFF\fP
.IP "\fB$HOME/.gcin/config/pho-in-row1\fP \fIboolean\fP"
Show key codes in first row of Bopomofo IM's window.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/phonetic-huge-tab\fP \fIboolean\fP" 
Use pho-huge.tab to input all of Traditional Chinese, Simplified Chinese, and Japanese Hanzi within Bopomofo and Tsin IM.
.PP
OPTIONS    MEANINGS
.br
1          ON
.br
\fB0          OFF\fP
.IP "\fB$HOME/.gcin/config/tsin-tone-char-input\fP \fIboolean\fP"
Input Bopomofo's tone sympols in Tsin IM.
.PP
OPTIONS    MEANINGS
.br
1          ON
.br
\fB0          OFF\fP
.IP "\fB$HOME/.gcin/config/tsin-tab-phrase-end\fP \fIboolean\fP"
Use Tab key to stop Tsin IM's phrase-auto-selection.
.PP
OPTIONS    MEANINGS
.br
1          ON
.br
\fB0          OFF\fP
.IP "\fB$HOME/.gcin/config/tsin-buffer-size\fP \fInumber\fP" 
Buffer size of editing area of Tsin IM. Default is \fB40\fP.
.IP "\fB$HOME/.gcin/config/tsin-phrase-line-color\fP \fIhex\fP" 
Color of phrase-underline within Tsin IM. Default is blue, \fB#0000FF\fP.
.IP "\fB$HOME/.gcin/config/tsin-cursor-color\fP \fIhex\fP"
Color of Tsin IM's cursor.
.PP
OPTIONS    MEANINGS
.br
#FF0000    Red
.br
#00FF00    Green
.br
\fB#0000FF    Blue\fP
.br
#FFFF00    Yellow
.br
#FF00FF    Magenta
.br
#00FFFF    Cyan
.IP "\fB$HOME/.gcin/config/gcin-font-size\fP \fInumber\fP" 
Font size of character-selection area. Default is \fB16\fP.
.IP "\fB$HOME/.gcin/config/gcin-font-size-symbol\fP \fInumber\fP" 
Font size of symbol-selection window. Default is \fB12\fP.
.IP "\fB$HOME/.gcin/config/gcin-font-size-tsin-presel\fP \fInumber\fP" 
Font size of phrase pre-selection window within Tsin IM. Default is \fB16\fP.
.IP "\fB$HOME/.gcin/config/gcin-font-size-tsin-pho-in\fP \fInumber\fP" 
Font size of phonetic input area of Bopomofo and Tsin IM. Default is \fB10\fP.
.IP "\fB$HOME/.gcin/config/gcin-font-size-pho-near\fP \fInumber\fP"
Font size of Tsin IM's alike-phonetic character-selection area. Default is \fB14\fP.
.IP "\fB$HOME/.gcin/config/gcin-font-size-gtab-in\fP \fInumber\fP" 
Font size of key codes input area of gtab IMs(Chanjei IM, Array IM, etc.). Default is \fB10\fP.
.IP "\fB$HOME/.gcin/config/gcin-font-name\fP \fIstring\fP"
Font used under gcin.
.PP
OPTIONS    MEANINGS
.br
\fBsans       Sans-serif\fP
.br
serif      Serif
.IP "\fB$HOME/.gcin/config/gcin-pop-up-win\fP \fIboolean\fP"
Pop up window on the right lower corner of screen.
.PP
OPTIONS    MEANINGS
.br
1          ON
.br
\fB0          OFF\fP
.IP "\fB$HOME/.gcin/config/gcin-pop-up-win-abs-corner\fP \fIboolean\fP"
Keep pop up window on the right lower corner of screen absolutely.
.PP
OPTIONS    MEANINGS
.br
1          ON
.br
\fB0          OFF\fP
.IP "\fB$HOME/.gcin/config/gcin-input-style\fP \fIboolean\fP"
Window style of gcin.
.PP
OPTIONS    MEANINGS
.br
\fB1          OverTheSpot\fP
.br
2          Root (Fixed index window)
.IP "\fB$HOME/.gcin/config/gcin-root-x\fP \fInumber\fP"
Window place in X axis when window style is Root (Fixed index window). Default is \fB1600\fP.
.IP "\fB$HOME/.gcin/config/gcin-root-y\fP \fInumber\fP"
Window place in Y axis when window style is Root (Fixed index window). Default is \fB1200\fP.
.IP "\fB$HOME/.gcin/config/gcin-inner-frame\fP \fIboolean\fP"
Show inner frame border of gcin window. If you want to apply some GTK's themes, you may want to toggle it on for better outlook.
.PP
OPTIONS    MEANINGS
.br
1          ON
.br
\fB0          OFF\fP
.IP "\fB$HOME/.gcin/config/gcin-status-tray\fP \fIboolean\fP"
Show gcin's status in system tray.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/gtab-dup-select-bell\fP \fIboolean\fP" 
Bell ring when multiple selections are available within gtab IMs.
.PP
OPTIONS    MEANINGS
.br
1          ON
.br
\fB0          OFF\fP
.IP "\fB$HOME/.gcin/config/gtab-space-auto-first\fP \fInumber\fP" 
Function of Space Key within gtab IMs.
.PP
OPTIONS    MEANINGS
.br
\fB0          Auto-selected by .gtab file's definition.\fP
.br
1          Send first character within Liu's IM(Boshiamy IM).
.br
2          Send first character within character-selection area.
.br
4          Does not send first character. (For Array IM)
.IP "\fB$HOME/.gcin/config/gtab-auto-select-by_phrase\fP \fIboolean\fP" 
Auto-selection by Tsin phrase database within gtab IMs.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/gtab-pre-select\fP \fIboolean\fP" 
Show auto-selection suggest from Tsin phrase database within gtab IMs.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/gtab-press-full-auto-send\fP \fIboolean\fP" 
Auto-send character when key codes input area is full. For gtab IMs.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/gtab-disp-partial-match\fP \fIboolean\fP" 
Display partial matched characters within gtab IMs.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/gtab-simple-win\fP \fIboolean\fP" 
Smaller window for gtab IMs.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/gtab-disp-key-codes\fP \fIboolean\fP" 
Show all possible key codes of character within gtab IMs.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/gtab-disp-im-name\fP \fIboolean\fP" 
Display input method name within gtab IMs.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/gtab-invalid-key-in\fP \fIboolean\fP" 
Clear key codes input area when invalid key and Space key are pressed.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/gtab-shift-phrase-key\fP \fIboolean\fP"
Use Shift single key to input Alt-Shift phrases within gtab IMs.
.PP
OPTIONS    MEANINGS
.br
1          ON
.br
\fB0          OFF\fP
.IP "\fB$HOME/.gcin/config/gtab-hide-row2\fP \fIboolean\fP"
Hide second row of gtab IMs' window.
.PP
OPTIONS    MEANINGS
.br
1          ON
.br
\fB0          OFF\fP
.IP "\fB$HOME/.gcin/config/gtab-in-row1\fP \fIboolean\fP"
Show key codes in first row of gtab IMs' window.
.PP
OPTIONS    MEANINGS
.br
1          ON
.br
\fB0          OFF\fP
.IP "\fB$HOME/.gcin/config/gtab-capslock-in-eng\fP \fIboolean\fP"
Input English/Numbers/Symbols directly when Caps Lock key is ON (Within gtab IMs).
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/default-input-method\fP \fInumber\fP" 
Default IM when gcin is called.
.PP
OPTIONS    MEANINGS
.br
0          Internal character code IM
.br
1          Chanjei IM version 3
.br
2          Chanjei IM version 5
.br
3          Bopomofo IM
.br
4          Chanjei IM version 3, easy symbols
.br
5          Pinyin IM
.br
\fB6          Tsin IM\fP
.br
7          Dayi IM
.br
8          Array IM, 30 keys version
.br
9          Liu's IM(Boshiamy IM)
.br
10         Simple Chanjei IM
.br
11         Japanese Kana and Kanji IM
.br
12         Greek letters IM
.IP "\fB$HOME/.gcin/config/gcin-flags-im-enabled\fP \fInumber\fP" 
Available IMs to be cyclic selected by Control-Shift.
.PP
OPTIONS    MEANINGS
.br
\fB2147483647 All IMs are enable.\fP
.br
2147475456 All IMs are disabled.
.PP
         1 Ctrl\-Alt\-0 Internal character code IM
.br
         2 Ctrl\-Alt\-1 Chanjei IM version 3
.br
         4 Ctrl\-Alt\-2 Chanjei IM version 5
.br
         8 Ctrl\-Alt\-3 Bopomofo IM is available
.br
        16 Ctrl\-Alt\-4 Chanjei IM version 3, easy symbols
.br
        32 Ctrl\-Alt\-5 Pinyin IM
.br
        64 Ctrl\-Alt\-6 Tsin IM
.br
       128 Ctrl\-Alt\-7 Dayi IM
.br
       256 Ctrl\-Alt\-8 Array IM, 30 keys version
.br
       512 Ctrl\-Alt\-9 Liu's IM(Boshiamy IM)
.br
      1024 Ctrl\-Alt\-\- Simple Chanjei IM
.br
      2048 Ctrl\-Alt\-= Japanese Kana and Kanji IM
.br
      4096 Ctrl\-Alt\-` Greek letters IM
.PP
2147475456 add number of IMs, then you get your own setup number. For example, you want only Bopomofo, Tsin, and Array IM. So you calculate 2147475456 + 8 + 64 + 256 = 2147475784.
.PP
echo 2147475784 > $HOME/.gcin/config/gcin-flags-im-enabled
.PP
Then you get it.
.IP "\fB$HOME/.gcin/config/gcin-im-toggle-keys\fP \fInumber\fP" 
Toggle Key for IM window ON/OFF.
.PP
OPTIONS    MEANINGS
.br
\fB0          Control-Space\fP
.br
1          Shift-Space
.br
2          Alt-Space
.br
3          Windows-Space
.IP "\fB$HOME/.gcin/config/gcin-remote-client\fP \fIboolean\fP" 
Remote application client support(using port 9999-). If you want to use gcin under \fBsu\fP or \fBsudo\fP environment, you should toggle this option ON.
.PP
OPTIONS    MEANINGS
.br
1          ON
.br
\fB0          OFF\fP
.IP "\fB$HOME/.gcin/config/gcin-shift-space-eng-full\fP \fIboolean\fP" 
Toggle into double-wide English character mode with Shift-Space.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.IP "\fB$HOME/.gcin/config/left-right-button-tips\fP \fIboolean\fP" 
Show button tips when mouse cursor stays on gcin window. Default is ON, but it will be set into OFF after \fBgcin-setup\fP is executed once.
.PP
OPTIONS    MEANINGS
.br
\fB1          ON\fP
.br
0          OFF
.SH "SEE ALSO" 
\fIgcin2tab\fP(1), \fIphoa2d\fP(1), \fIphod2a\fP(1), \fItsa2d32\fP(1), \fItsd2a32\fP(1), \fIsim2trad\fP(1), \fItrad2sim\fP(1), \fItslearn\fP(1), \fIjuyin-learn\fP(1), \fIgcin-gb-toggle\fP(1)
.SH "AUTHORS" 
.IP "Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>"
Wrote gcin and associated tools.
.br
.IP "Friend of Chanjei IM, Malaysia <www.chinesecj.com>" 
Author of original Chanjei IM version 5 table.
.IP "Dayi Co., Ltd. <http://www.dayi.com>" 
Author of Dayi IM.
