.TH GCIN 1 "21 JAN 2012" "GCIN 2.7.2" "gcin input method platform"
.SH NAME
ts-contribute \- tsin vocabulary uploader for gcin
.SH SYNOPSIS
.B ts-contribute
.SH DESCRIPTION
.B ts-contribute
is the tsin vocabulary uploader, which you can contribute your vocabulary
on tsin's shared archive. The shared archive could be downloaded using
.B ts-edit
\.
.SH SEE ALSO
.BR gcin (1),
.BR gcin-tools (1),
.BR tsa2d32 (1),
.BR tslearn (1).
.BR ts-edit (1).
.SH AUTHOR
ts-contribute was written by Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>.
