.TH GCIN 1 "21 JAN 2012" "GCIN 2.7.2" "gcin input method platform"
.SH NAME
ts-edit \- tsin vocabulary database editor for gcin
.SH SYNOPSIS
.B ts-edit
.SH DESCRIPTION
.B ts-edit
is the tsin vocabulary database editor, which you can search and delete
the database entries. This tool can be used to download the vocabularies
contributed by other users using
.B ts-contribute
as well.
.SH SEE ALSO
.BR gcin (1),
.BR gcin-tools (1),
.BR tsa2d32 (1),
.BR tslearn (1).
.BR ts-contribute (1).
.SH AUTHOR
ts-edit was written by Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>.
