.TH GCIN 1 "21 JAN 2008" "GCIN 1.3.8" "gcin input method platform"
.SH NAME
tsa2d32, tsd2a32, tsd2a, tsin2gtab-phrase \- gcin's Tsin tools
.SH SYNOPSIS
.B tsa2d32
.br
.B tsd2a32
.B [\fB-nousecount\fP]     
.br
.B tsd2a
.B [\fB-nousecount\fP]     
.br
.B tsin2gtab-phrase
src.gtab
outfile
.SH DESCRIPTION
.B tsa2d32
is a tool to import Tsin input method phrase database.
.PP
.B tsd2a32
is a tool to export Tsin input method phrase database.
.PP
.B tsd2a
is an old tool only for back-compatibility.
.B tsin2gtab-phrase
is a tool to extract phrases from gtab file.
.SH OPTIONS
.TP
.B \-nousecount
Do not record usecount when exporting phrase database of Tsin input method.
.SH ENVIRONMENT VARIABLES
.IP GCIN_NO_RELOAD
Tell gcin server do not reload data after execution of tsa2d32.
.SH SEE ALSO
.BR gcin (1),
.BR tslearn.
.SH AUTHOR
tsa2d32, tsd2a32, tsd2a and tsin2gtab-phrase were written by Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>.
