.TH GCIN 1 "21 JAN 2008" "GCIN 1.3.8" "gcin input method platform"
.SH NAME
tslearn \- learns user's personal phrase data
.SH SYNOPSIS
.B tslearn
.SH DESCRIPTION
.B tslearn
learns user's personal phrase data for Tsin input method.
.SH SEE ALSO
.BR gcin (1),
.BR tsa2d32 (1).
.SH AUTHOR
tslearn was written by Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>.
