.TH GCIN2TAB 1 "28 AUG 2006" "GCIN 1.2.3" "gcin's miscellaneous tools"
.SH NAME
gcin2tab, phoa2d, phod2a, tsa2d32, tsd2a32, tsd2a, sim2trad, trad2sim, tslearn, juyin-learn, gcin-gb-toggle \- gcin associated tools
.SH SYNOPSIS
.B gcin2tab
.RB [\| \-v \||\| \-\-version \|]
.IR file
.br
.B phoa2d
.br
.B phod2a
.br
.B tsa2d32
.br
.B tsd2a32
.RB [\| \-nousecount \|]
.br
.B tsd2a
.RB [\| \-nousecount \|]
.br
.B sim2trad
.br
.B trad2sim
.br
.B tslearn
.br
.B juyin-learn
.br
.B gcin-gb-toggle
.SH DESCRIPTION
.B gcin2tab
converts plain text input method(IM) table to gcin's .gtab format.
.PP
\fBphoa2d\fP converts $HOME/.gcin/pho.tab.src to $HOME/.gcin/pho.tab, which is used by Bopomofo and Tsin IM.
.PP
\fBphod2a\fP converts $HOME/.gcin/pho.tab to $HOME/.gcin/pho.tab.src, which may be edited by users.
.PP
\fBtsa2d32\fP and \fBtsd2a32\fP are tools for importing and exporting Tsin IM's phrase database. \fBtsd2a\fP is kept only for back-compatibility.
.PP
\fBsim2trad\fP and \fBtrad2sim\fP converts clipboard's data to Traditional Chinese and Simplified Chinese.
.PP
\fBtslearn\fP learns user's personal Tsin data online.
.PP
\fBjuyin-learn\fP searches Chinese characters' phonations.
.PP
\fBgcin-gb-toggle\fP toggles gcin's output between Traditional Chinese and Simplified Chinese.
.SH OPTIONS
.PP
.IP "\-h, \-v, \-\-version"
Show version of gcin2tab and exit.
.PP
.IP "\-nousecount"
Does not record usecount when exporting Tsin IM's phrase database.
.SH ENVIRONMENT VARIABLES
.IP GCIN_NO_RELOAD
.br
Tell gcin server not to reload after execution of phoa2d and tsa2d32.
.SH SEE ALSO
.IR gcin (1)
.SH AUTHOR
.IP "Edward Der-Hua Liu <cp76@csie.nctu.edu.tw>"
