#!/bin/sh
rm -fr debian
patch -p1 < $0
chmod 755 debian/rules
sed -i "s#9-9#`cat VERSION.gcin | sed -e 's/.pre/~pre/' -e 's/$/-2/'`#" debian/changelog
exec dpkg-buildpackage -b
--- a/debian/changelog
+++ b/debian/changelog
@@ -0,0 +1,5 @@
+gcin (9-9) experimental; urgency=low
+
+  * New snapshot.
+
+ -- Edward Liu <xxxx@yyy.org>  Wed, 14 Dec 2011 22:07:18 +0800
--- a/debian/ckqt.sh
+++ b/debian/ckqt.sh
@@ -0,0 +1,16 @@
+#!/bin/sh
+[ ! -e debian/gcin/usr/lib/qt4/plugins/inputmethods/im-gcin.so ] && sed -i 's/, gcin-qt4-immodule//' debian/gcin/DEBIAN/control
+[ ! -e debian/gcin/usr/lib/qt3/plugins/inputmethods/libqgcin.so ] && sed -i 's/, gcin-qt3-immodule//' debian/gcin/DEBIAN/control
+[ ! -e debian/gcin/usr/lib/gcin/chewing-module.so ] && sed -i 's/, libchewing3//' debian/gcin/DEBIAN/control
+if [ ! -e debian/gcin/usr/lib/gcin/anthy-module.so ]; then
+  grep -v 'Suggests: kasumi' debian/gcin/DEBIAN/control | sed 's/, anthy//' > debian/gcin/DEBIAN/control.in
+  mv debian/gcin/DEBIAN/control.in debian/gcin/DEBIAN/control
+fi
+if [ -d debian/gcin/usr/lib/gtk-3.0/immodules ]; then
+  mkdir -p debian/gcin/usr/lib/gtk-3.0/3.0.0
+  mv debian/gcin/usr/lib/gtk-3.0/immodules debian/gcin/usr/lib/gtk-3.0/3.0.0/
+fi
+mkdir -p debian/gcin/usr/lib/gtk-2.0/2.10.0
+mv debian/gcin/usr/lib/gtk-2.0/immodules debian/gcin/usr/lib/gtk-2.0/2.10.0/
+/usr/bin/gtk-query-immodules-2.0 debian/gcin/usr/lib/gtk-2.0/2.10.0/immodules/im-gcin.so | grep gcin | tail -n 1 >> debian/gcin/usr/lib/gtk-2.0/2.10.0/immodule-files.d/gcin.immodules
+true
--- a/debian/compat
+++ b/debian/compat
@@ -0,0 +1 @@
+7
--- a/debian/control
+++ b/debian/control
@@ -0,0 +1,27 @@
+Source: gcin
+Section: utils
+Priority: optional
+Maintainer: Edward Liu <xxxx@yyyy.org>
+Homepage: http://www.csie.nctu.edu.tw/~cp76/gcin/
+Vcs-Git: git://git.debian.org/git/users/koster/gcin.git
+Vcs-Browser: http://git.debian.org/?p=users/koster/gcin.git;a=summary
+Build-Depends: debhelper (>= 7.0.50~), libgtk2.0-dev (>= 2.10.0), libxtst-dev, dpkg | libgtk-3-dev | libqt4-dev | libqt3-mt-dev | libanthy-dev | libchewing3-dev
+Standards-Version: 3.9.1
+
+Package: gcin
+Architecture: any
+Depends: ${shlibs:Depends}, ${misc:Depends}
+Recommends: im-switch | im-config, anthy, libchewing3
+Suggests: kasumi
+Conflicts: gcin-dev, gcin-qt4-immodule, gcin-qt3-immodule
+Replaces: gcin-dev, gcin-qt4-immodule, gcin-qt3-immodule
+Provides: gcin-dev, gcin-qt4-immodule, gcin-qt3-immodule
+Description: an GTK+ based input method platform for Chinese users
+ Gcin is an input method platform, which supports GTK+/QT immodule and XIM.
+ Gcin is focused mainly on Traditional Chinese. However, it is also very useful
+ for Simplified Chinese, Japanese, and many other languages.
+ .
+ Input method table format of gcin is almost as same as those of xcin and scim.
+ .
+ This package contains an GTK+ immodule. If you want to use QT immodule, please
+ install gcin-qt3-immodule package.
--- a/debian/gcin.immodules
+++ b/debian/gcin.immodules
@@ -0,0 +1 @@
+"/usr/lib/gtk-2.0/2.10.0/immodules/im-gcin.so"
--- a/debian/im-switch/gcin
+++ b/debian/im-switch/gcin
@@ -0,0 +1,15 @@
+XIM=gcin
+XIM_PROGRAM=/usr/bin/gcin
+XIM_ARGS=
+GTK_IM_MODULE=gcin
+if [ ! -f /usr/lib/qt3/plugins/inputmethods/libqgcin.so ]; then
+  QT_IM_MODULE=xim
+else
+  QT_IM_MODULE=gcin
+fi
+if [ ! -f /usr/lib/qt4/plugins/inputmethods/im-gcin.so ]; then
+  QT4_IM_MODULE=xim
+else
+  export QT4_IM_MODULE=gcin
+fi
+DEPENDS=
--- a/debian/install
+++ b/debian/install
@@ -0,0 +1,4 @@
+im-client/gcin-im-client.h usr/include
+im-client/gcin-im-client-attr.h usr/include
+debian/im-switch/gcin etc/X11/xinit/xinput.d
+debian/gcin.immodules usr/lib/gtk-2.0/2.10.0/immodule-files.d
--- a/debian/postinst
+++ b/debian/postinst
@@ -0,0 +1,32 @@
+#!/bin/sh
+# postinst script for gcin
+
+set -e
+
+ua_inst () {
+	update-alternatives \
+        --install /etc/X11/xinit/xinput.d/$1 xinput-$1 \
+        /etc/X11/xinit/xinput.d/$2 $3 ;
+}
+
+[ -x /usr/bin/gtk-query-immodules-3.0 ] && /usr/bin/gtk-query-immodules-3.0 --update-cache
+
+case "$1" in
+    configure)
+        # Set up default
+        ua_inst all_ALL gcin  0
+        ua_inst zh_CN   gcin 30
+        ua_inst zh_TW   gcin 70
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+#DEBHELPER#
+
+exit 0
--- a/debian/prerm
+++ b/debian/prerm
@@ -0,0 +1,28 @@
+#!/bin/sh
+# prerm script for gcin
+
+set -e
+
+ua_remove () {
+	update-alternatives \
+        --remove xinput-$1 \
+        /etc/X11/xinit/xinput.d/$2 ;
+}
+
+[ -x /usr/bin/gtk-query-immodules-3.0 ] && /usr/bin/gtk-query-immodules-3.0 --update-cache
+
+case "$1" in
+    remove|upgrade|deconfigure)
+        ua_remove all_ALL gcin
+        ua_remove zh_CN   gcin
+        ua_remove zh_TW   gcin
+	;;
+    failed-upgrade)
+	;;
+    *)
+	echo "prerm called with unknown argument \`$1'" >&2
+	exit 1
+   ;;
+esac
+
+#DEBHELPER#
+
+exit 0
--- a/debian/rules
+++ b/debian/rules
@@ -0,0 +1,23 @@
+#!/usr/bin/make -f
+%:
+	dh $@
+
+override_dh_auto_configure:
+	sed -i 's~/usr/lib/~/usr/share/~' qt-im/Makefile
+	sed -i 's~/usr/$$(LIB)/~/usr/share/~' qt4-im/Makefile
+	sed -i 's~lib64~lib64foo~' configure
+	./configure --prefix=/usr --use_i18n=N --use_qt3=Y
+
+override_dh_auto_clean:
+	$(MAKE) clean
+	sed -i 's~/usr/share/~/usr/lib/~' qt-im/Makefile
+	sed -i 's~/usr/share/~/usr/$$(LIB)/~' qt4-im/Makefile
+	sed -i 's~lib64foo~lib64~' configure
+	dh_clean
+
+override_dh_shlibdeps:
+	dh_shlibdeps --exclude=libqgcin.so --exclude=im-gcin.so --exclude=anthy-module.so --exclude=chewing-module.so
+
+override_dh_gencontrol:
+	dh_gencontrol
+	sh debian/ckqt.sh
