#!/bin/sh
rm -fr debian
patch -p1 < $0
chmod 755 debian/rules
sed -i "s#9-9#`cat VERSION.gcin | sed -e 's/.pre/~pre/' -e 's/$/-0/'`#" debian/changelog
exec dpkg-buildpackage -b
--- a/debian/changelog
+++ b/debian/changelog
@@ -0,0 +1,5 @@
+gcin (9-9) experimental; urgency=low
+
+  * New snapshot.
+  
+ -- Kan-Ru Chen <koster@debian.org>  Mon, 28 Feb 2011 18:07:18 +0800
--- a/debian/ckqt.sh
+++ b/debian/ckqt.sh
@@ -0,0 +1,10 @@
+#!/bin/sh
+[ ! -e debian/gcin/usr/lib/qt4/plugins/inputmethods/im-gcin.so ] && sed -i 's/, gcin-qt4-immodule//' debian/gcin/DEBIAN/control
+[ ! -e debian/gcin/usr/lib/qt3/plugins/inputmethods/libqgcin.so ] && sed -i 's/, gcin-qt3-immodule//' debian/gcin/DEBIAN/control
+[ ! -e debian/gcin/usr/share/gcin/table/chewing-module.so ] && sed -i 's/, libchewing3//' debian/gcin/DEBIAN/control
+if [ ! -e debian/gcin/usr/share/gcin/table/anthy-module.so ]; then
+  grep -v 'Suggests: kasumi' debian/gcin/DEBIAN/control | sed 's/, anthy//' > debian/gcin/DEBIAN/control.in
+  mv debian/gcin/DEBIAN/control.in debian/gcin/DEBIAN/control
+fi
+/usr/lib/libgtk2.0-0/gtk-query-immodules-2.0 debian/gcin/usr/lib/gtk-2.0/2.10.0/immodules/im-gcin.so | grep gcin | tail -n 1 >> debian/gcin/usr/lib/gtk-2.0/2.10.0/immodule-files.d/gcin.immodules
+true
--- a/debian/compat
+++ b/debian/compat
@@ -0,0 +1 @@
+7
--- a/debian/control
+++ b/debian/control
@@ -0,0 +1,27 @@
+Source: gcin
+Section: utils
+Priority: optional
+Maintainer: Kan-Ru Chen <koster@debian.org>
+Homepage: http://www.csie.nctu.edu.tw/~cp76/gcin/
+Vcs-Git: git://git.debian.org/git/users/koster/gcin.git
+Vcs-Browser: http://git.debian.org/?p=users/koster/gcin.git;a=summary
+Build-Depends: debhelper (>= 7.0.50~), libgtk2.0-dev (>= 2.20.0), libxtst-dev, dpkg | libgtk-3-dev | libqt4-dev | libqt3-mt-dev | libanthy-dev | libchewing3-dev
+Standards-Version: 3.9.1
+
+Package: gcin
+Architecture: any
+Depends: ${shlibs:Depends}, ${misc:Depends}
+Recommends: im-switch | im-config, anthy, libchewing3
+Suggests: kasumi
+Conflicts: gcin-dev, gcin-qt4-immodule, gcin-qt3-immodule
+Replaces: gcin-dev, gcin-qt4-immodule, gcin-qt3-immodule
+Provides: gcin-dev, gcin-qt4-immodule, gcin-qt3-immodule
+Description: an GTK+ based input method platform for Chinese users
+ Gcin is an input method platform, which supports GTK+/QT immodule and XIM.
+ Gcin is focused mainly on Traditional Chinese. However, it is also very useful
+ for Simplified Chinese, Japanese, and many other languages.
+ .
+ Input method table format of gcin is almost as same as those of xcin and scim.
+ .
+ This package contains an GTK+ immodule. If you want to use QT immodule, please
+ install gcin-qt3-immodule package.
--- a/debian/gcin.immodules
+++ b/debian/gcin.immodules
@@ -0,0 +1 @@
+"/usr/lib/gtk-2.0/2.10.0/immodules/im-gcin.so" 
--- a/debian/gcin.xpm
+++ b/debian/gcin.xpm
@@ -0,0 +1,188 @@
+/* XPM */
+static char *gcin[] = {
+/* columns rows colors chars-per-pixel */
+"32 26 156 2",
+"   c #000000",
+".  c #0A0000",
+"X  c #0C0C00",
+"o  c #130000",
+"O  c #1B0000",
+"+  c #171700",
+"@  c #1D1600",
+"#  c #1D1D00",
+"$  c #2F0000",
+"%  c #370000",
+"&  c #3E0000",
+"*  c #262600",
+"=  c #2D2D00",
+"-  c #303000",
+";  c #3B3400",
+":  c #393900",
+">  c #440000",
+",  c #4C0400",
+"<  c #530000",
+"1  c #5A1100",
+"2  c #630000",
+"3  c #690000",
+"4  c #760000",
+"5  c #790000",
+"6  c #742C00",
+"7  c #444400",
+"8  c #4D4D00",
+"9  c #544E00",
+"0  c #535300",
+"q  c #5C5C00",
+"w  c #616100",
+"e  c #6C6C00",
+"r  c #706A00",
+"t  c #727200",
+"y  c #787200",
+"u  c #820000",
+"i  c #920000",
+"p  c #9D0000",
+"a  c #A60000",
+"s  c #AA0000",
+"d  c #B70000",
+"f  c #BF0000",
+"g  c #B42B00",
+"h  c #8E6B00",
+"j  c #C20000",
+"k  c #CB0000",
+"l  c #D20000",
+"z  c #DD0000",
+"x  c #DD0B00",
+"c  c #DD1402",
+"v  c #DE1B04",
+"b  c #DE2207",
+"n  c #DE2408",
+"m  c #DE2A07",
+"M  c #DE2B0A",
+"N  c #DF340E",
+"B  c #DF3A0F",
+"V  c #DF3B11",
+"C  c #E00000",
+"Z  c #E21500",
+"A  c #E01D00",
+"S  c #E32C00",
+"D  c #E73500",
+"F  c #E0360E",
+"G  c #E53D00",
+"H  c #E03D12",
+"J  c #E94C00",
+"K  c #E04214",
+"L  c #E04518",
+"P  c #E04A16",
+"I  c #E14B1A",
+"U  c #E1521E",
+"Y  c #E25722",
+"T  c #E25C25",
+"R  c #EA6400",
+"E  c #E16327",
+"W  c #E36A2E",
+"Q  c #E36C32",
+"!  c #E47233",
+"~  c #E57438",
+"^  c #E27A36",
+"/  c #E57C3C",
+"(  c #E67E40",
+")  c #838300",
+"_  c #8A8A00",
+"`  c #959400",
+"'  c #9B9B00",
+"]  c #AE8300",
+"[  c #A3A500",
+"{  c #A4A900",
+"}  c #ADB100",
+"|  c #B2B200",
+" . c #BABA00",
+".. c #CABE00",
+"X. c #F08400",
+"o. c #E5803D",
+"O. c #E2BD00",
+"+. c #E58342",
+"@. c #E68B44",
+"#. c #E58B4B",
+"$. c #E88F4A",
+"%. c #E4944D",
+"&. c #E8914D",
+"*. c #E79652",
+"=. c #E49952",
+"-. c #E89352",
+";. c #E99E54",
+":. c #E99C5A",
+">. c #E6A45D",
+",. c #E9A25C",
+"<. c #E4AD64",
+"1. c #EAA964",
+"2. c #ECAE6C",
+"3. c #EBB26F",
+"4. c #E3B270",
+"5. c #E4B977",
+"6. c #EDB674",
+"7. c #EBBA76",
+"8. c #EDBC7B",
+"9. c #C5C500",
+"0. c #CBCB00",
+"q. c #D2CB00",
+"w. c #D0D000",
+"e. c #DDDD00",
+"r. c #E5D400",
+"t. c #F2CA00",
+"y. c #E2E200",
+"u. c #E6EA00",
+"i. c #E9E900",
+"p. c #F4F400",
+"a. c yellow",
+"s. c #EEC27C",
+"d. c #EDC483",
+"f. c #EEC68B",
+"g. c #EEC987",
+"h. c #EECB8D",
+"j. c #EFCE90",
+"k. c #E5D295",
+"l. c #EFD594",
+"z. c #EDDA9E",
+"x. c #F0C98E",
+"c. c #F0CC91",
+"v. c #F0D093",
+"b. c #F1D59C",
+"n. c #F1D89D",
+"m. c #EFDDA2",
+"M. c #EFDEA8",
+"N. c #F2DBA1",
+"B. c #F4DEAA",
+"V. c #F2E0A5",
+"C. c #F3E1AC",
+"Z. c #F4E5B2",
+"A. c #F5E9BB",
+"S. c #F6EEC4",
+"D. c #F7EEC9",
+"F. c None",
+/* pixels */
+"F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.a z z z z l < F.F.F.F.F.F.F.F.F.",
+"F.F.F.F.o o o F.F.F.F.F.F.o O 3 l z v F v z k > F.o o F.F.F.F.F.",
+"F.o 2 d j j j j j i 2 i j j j z z v ^ <.E x z k f j f j i % F.F.",
+"> d z z z z z z z z z z z z z z z v =.k./ x z z z z z z C j & F.",
+"s z z c F I F b n c z z v B P V b c E %.I x b n M V V v C z j > ",
+"z z v ! 7.x.7.;.>.Y x N +.8.h.d.-.N W >.U m #.=.,.d.g.-.H z z u ",
+"z x T v.Z.g.g.Z.A./ m -.C.N.d.h.4.U =.M.~ K f.S.l.d.N.Z.+.c z k ",
+"z v :.A.,.K U x.D.+.U b.n.! V I I N :.Z.~ V j.S.@.B / Z.6.S z z ",
+"z M 6.Z.W x v :.A.( ~ Z.2.S z z z v :.C.~ V c.v.L z Y n.8.N z z ",
+"z N 8.B.T z c -.Z.( ( A.>.c z z z v :.Z.~ V x.j.K z I n.d.N z z ",
+"z n 2.A./ c S 3.S.( ! Z.6.N z z x v :.Z.~ K j.j.K z Y b.d.N z z ",
+"z c +.Z.x.o.&.V.D./ P x.V.&.E W Q V :.Z.~ K j.k.K z U n.d.N z z ",
+"z z V 1.C.C.m.V.A./ v ( b.C.n.z.5.U =.z.! K d.d.K z U h.8.V z z ",
+"z z x I / %.o.s.C.Q z S W >.6.1.^ M Y @.L n ^ o.n z N @.^ v z j ",
+"z z M +.=.@.>.C.x.I z z x v S n c z x v x z c c x z z v c z z 2 ",
+"z z V <.m.B.B.j.~ Z c R c z C C z z z z z J m z z z l z z z 4 F.",
+"p z c U / @./ Y v z v t.g s s s s 5 F.F.F.h O.1 F., 6 , > > F.F.",
+"3 z z C x x x G G D J r.0 ; y r F.` { { [ | i.} { | u.q F.F.F.F.",
+"F.5 k z z z z X.r...q.p.0.9.y.0.F.0 w y e.t q | e.e w - F.F.F.F.",
+"F.F.% < < < F.] _ F.* 9.* F._ ) F.F.F.+  .= F.` _ F.F.F.F.F.F.F.",
+"F.F.F.F.F.F.F.) ' * 7 w.7 * ' ) F.F.F.F._ _ + e.t F.F.F.F.F.F.F.",
+"F.F.F.F.F.F.F.) y.0.0.p.0.0.i.) F.F.F.F.7 w.) 0.# F.F.F.F.F.F.F.",
+"F.F.F.F.F.F.F.: 7 F.= 0.= F.7 : F.F.F.F.F.[ a.) F.F.F.F.F.F.F.F.",
+"F.F.F.F.F.F.F.F.F.F.# 0.# F.F.F.F.F.F.F.0 9.p.9.0 F.F.F.F.F.F.F.",
+"F.F.F.F.F.F.F.F.F.F.# 9.# F.F.F.F.X 0 ` y.[ 8 | i.` 0 X F.F.F.F.",
+"F.F.F.F.F.F.F.F.F.F.# 0.# F.F.F.F.' p.0.0 X F.+ _ p.p.t F.F.F.F."
+};
--- a/debian/im-switch/gcin
+++ b/debian/im-switch/gcin
@@ -0,0 +1,6 @@
+XIM=gcin
+XIM_PROGRAM=/usr/bin/gcin
+XIM_ARGS=
+GTK_IM_MODULE=gcin
+QT_IM_MODULE=gcin
+DEPENDS=
--- a/debian/install
+++ b/debian/install
@@ -0,0 +1,5 @@
+im-client/gcin-im-client.h usr/include
+im-client/gcin-im-client-attr.h usr/include
+debian/im-switch/gcin etc/X11/xinit/xinput.d
+debian/gcin.xpm usr/share/pixmaps
+debian/gcin.immodules usr/lib/gtk-2.0/2.10.0/immodule-files.d
--- a/debian/links
+++ b/debian/links
@@ -0,0 +1,9 @@
+usr/share/man/man1/gcin-setup.1.gz usr/share/man/man1/gcin-setup-tab.1.gz
+usr/share/man/man1/phoa2d.1.gz usr/share/man/man1/phod2a.1.gz
+usr/share/man/man1/sim2trad.1.gz usr/share/man/man1/trad2sim.1.gz
+usr/share/man/man1/tsa2d32.1.gz usr/share/man/man1/tsd2a.1.gz
+usr/share/man/man1/tsa2d32.1.gz usr/share/man/man1/tsd2a32.1.gz
+usr/share/man/man1/tsa2d32.1.gz usr/share/man/man1/tsin2gtab-phrase.1.gz
+usr/lib/menu/gcin usr/share/menu/gcin
+usr/lib/gtk-2.0/immodules/im-gcin.so usr/lib/gtk-2.0/2.10.0/immodules/im-gcin.so
+usr/lib/gtk-3.0/immodules/im-gcin.so usr/lib/gtk-3.0/3.0.0/immodules/im-gcin.so
--- a/debian/postinst
+++ b/debian/postinst
@@ -0,0 +1,32 @@
+#!/bin/sh
+# postinst script for gcin
+
+set -e
+
+ua_inst () {
+	update-alternatives \
+        --install /etc/X11/xinit/xinput.d/$1 xinput-$1 \
+        /etc/X11/xinit/xinput.d/$2 $3 ;
+}
+
+case "$1" in
+    configure)
+        # Set up default
+        ua_inst all_ALL gcin  0
+        ua_inst zh_CN   gcin 30
+        ua_inst zh_TW   gcin 50
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+#DEBHELPER#
+
+exit 0
--- a/debian/prerm
+++ b/debian/prerm
@@ -0,0 +1,28 @@
+#!/bin/sh
+# prerm script for gcin
+
+set -e
+
+ua_remove () {
+	update-alternatives \
+        --remove xinput-$1 \
+        /etc/X11/xinit/xinput.d/$2 ;
+}
+
+case "$1" in
+    remove|upgrade|deconfigure)
+        ua_remove all_ALL gcin
+        ua_remove zh_CN   gcin
+        ua_remove zh_TW   gcin
+	;;
+    failed-upgrade)
+	;;
+    *)
+	echo "prerm called with unknown argument \`$1'" >&2
+	exit 1
+   ;;
+esac
+
+#DEBHELPER#
+
+exit 0
--- a/debian/rules
+++ b/debian/rules
@@ -0,0 +1,23 @@
+#!/usr/bin/make -f
+%:
+	dh $@
+
+override_dh_auto_configure:
+	sed -i 's~/usr/lib/~/usr/share/~' qt-im/Makefile
+	sed -i 's~/usr/lib/~/usr/share/~' qt4-im/Makefile
+	sed -i 's~lib64~lib64foo~' configure
+	./configure --prefix=/usr --use_i18n=Y --use_qt3=Y
+
+override_dh_auto_clean:
+	$(MAKE) clean
+	sed -i 's~/usr/share/~/usr/lib/~' qt-im/Makefile
+	sed -i 's~/usr/share/~/usr/lib/~' qt4-im/Makefile
+	sed -i 's~lib64foo~lib64~' configure
+	dh_clean
+
+override_dh_shlibdeps:
+	dh_shlibdeps --exclude=libqgcin.so --exclude=im-gcin.so --exclude=anthy-module.so --exclude=chewing-module.so
+
+override_dh_gencontrol:
+	dh_gencontrol
+	sh debian/ckqt.sh
