#!/bin/bash -f
ulimit -c unlimited
rm -f core.*
export PATH=.:$PATH
export GCIN_TABLE_DIR=./data
echo "GCIN_TABLE_DIR=$GCIN_TABLE_DIR"
export GCIN_IM_CLIENT_NO_AUTO_EXEC=
pkill gcin.test
unset LC_CTYPE
export LC_CTYPE=zh_TW.UTF-8
#export LANG=zh_TW
export XMODIFIERS=@im=gcin_test
#export GCIN_OUTPUT_FILTER=./gcin_filter
export GCIN_ERR_COREDUMP
./gcin.test &
gcinpid=$!
sleep 1
export LD_PRELOAD="./gtk-im/im-gcin-cur.so"
export LD_LIBRARY_PATH="./im-client"
export GTK_IM_MODULE=gcin
#sleep 5; gcin-message -text 'abcde' -duration 5000;
gedit a.txt
#leafpad
#pcmanx
#firefox
#mozilla-thunderbird
#~/eclipse/eclipse
pkill gcin.test
