#!/bin/sh -f
export LC_ALL=zh_TW.UTF-8
export LANG=zh_TW.UTF-8
export LANGUAGE=zh_TW.UTF-8
export GCIN_TABLE_DIR=./data
echo "GCIN_TABLE_DIR=$GCIN_TABLE_DIR"
export GCIN_XIM=gcin.utf8
pkill gcin.test
export XMODIFIERS=@im=$GCIN_XIM
./gcin.test &
gcinpid=$!
sleep 1
locale
gedit
pkill gcin.test
