#!/bin/bash
export PATH=.:$PATH
export GCIN_TABLE_DIR=./data
echo "GCIN_TABLE_DIR=$GCIN_TABLE_DIR"
export GCIN_IM_CLIENT_NO_AUTO_EXEC=
pkill gcin.test
export LC_CTYPE=zh_CN.GB2312
#export LC_ALL=zh_CN.GB2312
export LC_CTYPE=zh_TW.Big5
export XMODIFIERS=@im=gcin_test
./gcin.test &
gcinpid=$!
sleep 1
export GTK_IM_MODULE=xim
gedit
