#!/bin/bash

export LC_CTYPE=zh_TW.UTF-8
#export GTK_IM_MODULE=xim
export GTK_IM_MODULE=scim
export XMODIFIERS=@im=SCIM
#scim -d &
#scim-input-pad &
#gedit --new-window &
#mozilla-firefox
#kedit
gedit
#leafpad
#amsn
#abiword

#export LD_LIBRARY_PATH=/usr/lib/firefox
#$LD_LIBRARY_PATH/mozilla-firefox-bin

#cd ~/fm
#./freemind.sh
