#!/bin/bash
export PATH=.:$PATH
export GCIN_TABLE_DIR=../data
echo "GCIN_TABLE_DIR=$GCIN_TABLE_DIR"
export GCIN_IM_CLIENT_NO_AUTO_EXEC=
pkill gcin.test
#export LC_CTYPE=zh_TW.UTF-8
#export LC_ALL=zh_TW.UTF-8
#export LANG=zh_TW.UTF-8
#export LC_CTYPE=zh_CN.UTF-8
#export LC_ALL=zh_CN.UTF-8
#export LANG=zh_CN.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export XMODIFIERS=@im=gcin_test
locale
../gcin.test &
gcinpid=$!
sleep 1
#export LD_PRELOAD=../im-client/libgcin-im-client.so
export GTK_IM_MODULE=xim
gedit
#kedit
