#!/bin/bash
export PATH=.:$PATH
export GCIN_TABLE_DIR=../data
echo "GCIN_TABLE_DIR=$GCIN_TABLE_DIR"
export GCIN_IM_CLIENT_NO_AUTO_EXEC=
pkill gcin.test
export LC_CTYPE=zh_TW.Big5
export LC_CTYPE=zh_TW.UTF-8
export XMODIFIERS=@im=gcin_test
export GTK_IM_MODULE=xim
locale
../gcin.test --g-fatal-warnings &
gcinpid=$!
sleep 1
gedit
#leafpad
#amsn
#ie6
#firefox
pkill gcin.test
