#!/bin/bash
export PATH=.:$PATH
export GCIN_TABLE_DIR=../data
echo "GCIN_TABLE_DIR=$GCIN_TABLE_DIR"
export GCIN_IM_CLEINT_NO_AUTO_EXEC=
pkill gcin.test
export LC_CTYPE=zh_TW.Big5
export XMODIFIERS=@im=gcin_test
export GTK_IM_MODULE=xim
../gcin.test &
gcinpid=$!
sleep 1
# gedit
#leafpad
amsn
